AddonId: GetchuMetadata
Packages:
- PackageUrl: https://github.com/erri120/Playnite.Extensions/releases/download/v2.5.6/GetchuMetadata.pext
  ReleaseDate: '2023-02-05'
  RequiredApiVersion: 6.8.0
  Version: 2.5.6
- PackageUrl: https://github.com/erri120/Playnite.Extensions/releases/download/v2.5.5/GetchuMetadata.pext
  ReleaseDate: '2022-05-12'
  RequiredApiVersion: 6.2.2
  Version: 2.5.5
- PackageUrl: https://github.com/erri120/Playnite.Extensions/releases/download/v2.5.4/GetchuMetadata.pext
  ReleaseDate: '2022-05-12'
  RequiredApiVersion: 6.2.2
  Version: 2.5.4
